# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id_media', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('autor', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=30)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='id_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tipo'),
        ),
    ]
