# Generated by Django 2.1 on 2018-09-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id_nombre_clip', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('seg_ini', models.TimeField()),
                ('seg_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id_media', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('autor', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=30)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(blank=True, max_length=30)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Categoria')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images')),
                ('country', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Usuario'),
        ),
        migrations.AddField(
            model_name='clip',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Media'),
        ),
        migrations.AddField(
            model_name='clip',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Usuario'),
        ),
    ]
