# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id_nombre_clip', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('seg_ini', models.TimeField()),
                ('seg_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30)),
                ('foto', models.CharField(blank=True, max_length=1000)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=204)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='media',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='media',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='media',
            name='tipo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.AddField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
        migrations.AddField(
            model_name='clip',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Media'),
        ),
        migrations.AddField(
            model_name='clip',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
        migrations.AddField(
            model_name='media',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
    ]
