# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20180825_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='usuario',
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
