# Generated by Django 2.1 on 2018-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180901_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tipo',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
