# Generated by Django 2.1 on 2018-09-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180902_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='tipo',
        ),
    ]
